var app = angular.module('emailApp',['ui.router']);
function config($stateProvider,$urlRouterProvider){
    $stateProvider
        .state('emails',{
            url:'/email',
            templateUrl:'views/new.html',
            data:{
                title:"email"
            }
        })
        .state('emails.view1',{
            url:'/view1',
            templateUrl:'subViews/view1.html'
        })
        .state('emails.view2',{
            url:'/view2',
            templateUrl:'subViews/view2.html'
        })
        .state('emails.view3',{
            url:'/view3',
            templateUrl:'subViews/view3.html'
        })
        .state('account',{
            url:'/acc',
            templateUrl:'views/account.html',
            data:{
                title:"账户"
            }
        })
        .state('account.view1',{
            url:'/view1',
            templateUrl:'subViews/view1.html'
        })
        .state('account.view2',{
            url:'/view2',
            templateUrl:'subViews/view2.html'
        })
        .state('account.view3',{
            url:'/view3',
            templateUrl:'subViews/view3.html'
        })
        .state('files',{
            url:'/files',
            templateUrl:'views/files.html',
            data:{
                title:"其他邮件"
            }
        })
}
app.config(config)